window:
  width: 800
  height: 600
  background_color: [255, 255, 255]
  title: "Ground Robot Navigation Simulation"
  FPS: 60

cars:
  - id: car1
    position: [400, 200]
    angle: 0
    speed: 0.75
    size: [40, 20]
    
    subjects: # Optional subjects for the car
      - type: "OccupancyGrid"
        resolution: 10
        mode: "minimap"
        position: [5, 5]
        size: [200, 200]
      - type: "DistanceSensor"
        range: 300
        resolution: 1
      - type: "2D Lidar"
        num_points: 120
        range:  300
        resolution: 1
      - type: "IMU"
        resolution: 1
    
    channels:
      - type: "Publisher Channels"
        channels: ["Points"]
      - type: "Subscriber Channels"
        channels: ["Points"]

  # - id: car2
  #   position: [700, 500]
  #   angle: 180
  #   speed: 1.0
  #   size: [35, 18]
    
  #   subjects: # Optional subjects for the car
  #     - type: "OccupancyGrid"
  #       resolution: 15
  #       mode: "minimap"
  #       position: [600, 5]
  #       size: [180, 180]
  #     - type: "2D Lidar"
  #       num_points: 90
  #       range:  250
  #       resolution: 1
  #     - type: "IMU"
  #       resolution: 1
    
  #   channels:
  #     - type: "Publisher Channels"
  #       channels: ["Points"]
  #     - type: "Subscriber Channels"
  #       channels: ["Points"]

obstacles:
  - [200, 150, 100, 100]
  - [500, 100, 50, 300]
  - [300, 400, 250, 50]
  - [100, 300, 80, 80]
  - [600, 350, 60, 120]

server:
  - host: "localhost"
    port: 6379
    channels: ["points"]
