window:
  width: 800
  height: 600
  background_color: [255, 255, 255]
  title: "Car Simulation Window"

cars:
  - id: car1
    position: [400, 200]
    angle: 0
    speed: 0.75
    subjects: # Optional subjects for the car
      - type: "OccupancyGrid"
        position: [300, 250]
        speed: 0.5
      - type: "DistanceSensor"
        position: [500, 300]
        state: "green"
      - type: "2D Lidar"
        position: [600, 400]
        state: "red"

  - id: car2
    position: [700, 500]
    angle: 180
    speed: 2

obstacles:
  - [200, 150, 100, 100]
  - [500, 100, 50, 300]
  - [300, 400, 250, 50]

server:
  - host: "localhost"
    port: 6379